name: Deploy para Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          server-dir: ${{ secrets.REMOTE_DIR }}/
          local-dir: ./
          exclude: |
            **/.git/**
            **/.git*
            **/.github/**
            **/node_modules/**
            **/vendor/**
            **/PHPMailer-master/**
            **/.vs/**
            **/.vscode/**
            **/*.sql
            **/*.zip
            **/.env
            **/*.log
            **/uploads/**
            **/img/**
          log-level: verbose
